name: Generate Snake

on:
  # Permite rodar o script manualmente na aba Actions
  workflow_dispatch:
  # Roda automaticamente todo dia à meia-noite
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # Puxa o seu nome de usuário automaticamente
          github_user_name: ${{ github.repository_owner }}
          # Gera a imagem na pasta dist
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
